### ISSUE TITLE
String and str types under Julia

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-julia#1]
Go to our [live SoS server](http://128.135.144.117:8000/), New SoS notebook.

In a `SoS` cell, enter

```
sos_string='X'
```

In a new cell, select `Julia`,

```
Int(sos_string)
```
fails with

```
MethodError: Cannot `convert` an object of type String to an object of type Int64
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.

 in Int64(::String) at ./sysimg.jl:53
 in include_string(::String, ::String) at ./loading.jl:441
```

while 
```
Int('X')
```
works.

So it turns out that `sos_string` is of type `String` and `X` is of type `str`.

My understanding is that
```
Int('X')
```
tries to convert a character to its integer value, but here `sos_string` is a `String` type that does not fall back to `str`, thus the error.

@HenryLeongStat : Could you have a look and explain what `String` is?
@gaow : Could you send the ticket to someone who knows Julia well, let him test this even all the Julia types, and let us know the intended behaviors?

**Comment by HenryLeongStat** [comment]
I don't think it is the problem of `SoS`, in `Julia`, we can't do something like that (Int(character)) as well.

<img width="696" alt="screen shot 2017-11-13 at 2 44 51 pm" src="https://user-images.githubusercontent.com/26916551/32748255-54d0142a-c881-11e7-8ae6-0ca8443bb610.png">

**Comment by BoPeng** [comment]
Yes, our transferred `X` is of type `String` (according to the error message) and literal `X` has type `str`. The former cannot be converted to integer with function `Int`, the latter can.

**Comment by BoPeng** [comment]
So we need to figure out what are these two types, which one should be better for Python transferred `str`.

**Comment by HenryLeongStat** [comment]
In `Julia`, I can't run the command `Int('X')` without getting the error message.
<img width="614" alt="screen shot 2017-11-13 at 2 54 43 pm" src="https://user-images.githubusercontent.com/26916551/32748708-ad7fdcb2-c882-11e7-9c06-72d04d0ffbb0.png">

However, I can do that in `Julia` kernel in `SoS` environment:
<img width="193" alt="screen shot 2017-11-13 at 2 55 50 pm" src="https://user-images.githubusercontent.com/26916551/32748738-c4f16992-c882-11e7-9131-ff1bdf7df266.png">

Also, I can run that in `Julia` environment as well:
<img width="189" alt="screen shot 2017-11-13 at 2 56 40 pm" src="https://user-images.githubusercontent.com/26916551/32748813-f6f8fa5e-c882-11e7-8fb6-8e3a310673df.png">

**Comment by HenryLeongStat** [comment]
Interesting, `julia` on my end is the same version in `jupyter notebook`, but we get the different results.

<img width="536" alt="screen shot 2017-11-13 at 2 58 30 pm" src="https://user-images.githubusercontent.com/26916551/32748943-665fc5f8-c883-11e7-86e5-08e1a0d2819c.png">

<img width="590" alt="screen shot 2017-11-13 at 2 58 37 pm" src="https://user-images.githubusercontent.com/26916551/32748951-699c80ee-c883-11e7-93a9-a07aa16c2c52.png">

**Comment by HenryLeongStat** [comment]
OK, I found out the reason.

For `Julia`, the type of `'X'` (with single quote) is, indeed, `Char`. However, the type of `"X"` (with double quote) is, indeed, `String`. 
 
It means that we cannot define something like `'XXX'`, because it should be `String`, not `Char`, so the error will show up if we define a `String` as `Char`, implementing by using single quote:

<img width="296" alt="screen shot 2017-11-13 at 3 09 09 pm" src="https://user-images.githubusercontent.com/26916551/32749311-9ea9e92e-c884-11e7-8bb0-a8abee1298f2.png">

**Comment by HenryLeongStat** [comment]
The solution I suggest is that, if the length of the `string` in `SoS` is 1, use `Char`. Otherwise, use `String`.

**Comment by BoPeng** [comment]
But can `char` be used when `string` is needed? Otherwise `"ab"` and `"a"` passed from SoS would behave quite differently.

**Comment by HenryLeongStat** [comment]
Base on the documentation of `Julia`, it claims that:

As in Java, **_strings are immutable_**: the value of an AbstractString object cannot be changed. To construct a different string value, you construct a new string from parts of other strings.

Also, `String` in `Julia` supports the full range of Unicode characters via the UTF-8 encoding.

However, for `Char`, it is just a special kind of 32-bit primitive type whose **_numeric value represents a Unicode code point._**

**Comment by HenryLeongStat** [comment]
And no, `char` can't be used when `string` is needed.

For example, in `julia`, we can do something like `"A" * "A"`, resulting in "AA".

However, we can't do something like `'A' * 'A'`, or `"A" * 'A'`

**Comment by BoPeng** [comment]
But does `Char` supports the usual `String` operations such as length?

**Comment by HenryLeongStat** [comment]
Yes, it does support `length()`. 
However, I think that people would more likely to use `String` to operate something like combining the two separate `String` together, but we can't do that with `Char` + `String` or `Char` + `Char`

**Comment by BoPeng** [comment]
But the documentation is completely off about this, and perhaps also about other types? https://vatlab.github.io/sos-docs/doc/documentation/Supported_Languages.html#Julia-123

**Comment by HenryLeongStat** [comment]
Comparing with `String` and `Char` in `Julia`
<img width="489" alt="screen shot 2017-11-13 at 3 27 22 pm" src="https://user-images.githubusercontent.com/26916551/32750119-45c33420-c887-11e7-8617-ec7ccea30eb4.png">

**Comment by BoPeng** [comment]
Please update the documentation and give some examples, perhaps using this ticket as an example.

**Comment by HenryLeongStat** [comment]
The documentation should be correct, because for now, we don't use `Char` for converting no matter the length of `str` in `Python` is 1 or >1.

<img width="278" alt="screen shot 2017-11-13 at 3 31 13 pm" src="https://user-images.githubusercontent.com/26916551/32750265-c3ebc268-c887-11e7-977d-532b32c22740.png">

**Comment by BoPeng** [comment]
I see `str` on both sides (Python and Julia) on the documentation, I suppose the Julia side should be `String`?

**Comment by HenryLeongStat** [comment]
So should we change the `julia kernel` to something like: if the length of `string` in `SoS` is 1, then it will become `Char` in `julia`? 

I don't quite suggest to do that because we cannot operate something like combining two `Char` or `Char` + `String`...

But another case is that, we cannot convert `String` with 1 length to `Int` in `Julia`...

**Comment by HenryLeongStat** [comment]
Oops, I see...

**Comment by BoPeng** [comment]
Because Python does not have these two types, it does not make sense to convert python `str` to `char`. I do not think we should change our behavior, but we do need to document the behavior and explain why.

**Comment by BoPeng** [comment]
Also, in the documentation, we should not say `%put` because we usually use `%get` from the subkernel. I suppose we should rephrase the tables as `from kernel`, `to kernel` etc.

**Comment by HenryLeongStat** [comment]
Understood! I agree since `Char` isn't really useful and it does cause the confusion...
