### ISSUE TITLE
SoS magic don't work when there is a comment above them

### ISSUE THREAD

**Issue by yanivabir** [vatlab/sos-julia#16]
If the first line in a chunk is a comment, %get magic doesn't work:

```
# Comment

%get dat --from R
```

Results in the following message: 
```
Unrecognized magic %get.

Julia does not use the IPython %magic syntax. To interact with the IJulia kernel, use IJulia.somefunction(...), for example. Julia macros, string macros, and functions can be used to accomplish most of the other functionalities of IPython magics.
```

However, running the same in SoS works, and moving the comment down in the chunk also runs without problem.

**Comment by BoPeng** [comment]
The rule (we should have documented it better) is that magics after a blank line are sent to the subkernel to be interpreted as subkernel magic. The SoS cells behave differently because the underyling "subkernel" is still SoS.
